apiVersion: v1
kind: Secret
metadata:
  name: mosaic-secret
type: Opaque
stringData:
  # Set these via `kubectl create secret generic mosaic-secret --dry-run=client -o yaml --from-literal=...`
  MOSAIC_OPENAI_API_KEY: ""
  MOSAIC_ANTHROPIC_API_KEY: ""
